name: ECR Publish
on:
  push:
    branches:
      - "main"

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: mentumfileupload
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::8} .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::8}

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:${GITHUB_SHA::8} $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

      - name: Restart Amazon ECS task
        env:
          CLUSTER: mentum
          SERVICE: file-service-service
          REGION: us-west-2
        run: |
          aws ecs update-service --force-new-deployment --cluster $CLUSTER --service $SERVICE --region $REGION &
