name: Tests
on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.4
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests
        run: |
          cp mentumfileupload/.env.example mentumfileupload/.env
          python manage.py test
